docker:
  dialect: postgres
  datasource: dbname=userservicedb user=postgres password=159753 sslmode=disable port=5556
  dir: migrations
  table: migrations

local:
  dialect: postgres
  datasource: dbname=userservicedb user=postgres password=159753 sslmode=disable port=5432
  dir: migrations
  table: migrations